django/tutorial/mysite/mysite/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^polls/', include('polls.urls',namespace='polls')),
    url(r'^admin/', include(admin.site.urls)),
)

django/tutorial/mysite/polls/urls.py
from django.conf.urls import patterns, url
from polls import views


urlpatterns = patterns('',
    # ex: /polls/
    url(r'^$', views.index, name='index'),
    # ex: /polls/5/
    url(r'^(?P<poll_id>\d+)/$', views.detail, name='detail'),
    # ex: /polls/5/results/
    url(r'^(?P<poll_id>\d+)/results/$', views.results, name='results'),
    # ex: /polls/5/vote/
    url(r'^(?P<poll_id>\d+)/vote/$', views.vote, name='vote'),
)

django/tutorial/mysite/polls/models.py
from django.db import models
from django.utils import timezone
import datetime
# Create your models here.
class Poll(models.Model):
    def __unicode__(self):
        return(self.question)

    def was_published_recently(self):
        return(self.pub_date>=timezone.now() - datetime.timedelta(days=1))
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean=True
    was_published_recently.short_description='Published Recently?'

    question=models.CharField(max_length=200)
    pub_date=models.DateTimeField('date published')


class Choice(models.Model):
    def __unicode__(self):
        return(self.choice_text)

    poll = models.ForeignKey(Poll)
    choice_text=models.CharField(max_length=200)
    votes=models.IntegerField(default=0)

django/tutorial/mysite/polls/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse, Http404
from django.template import RequestContext, loader
from polls.models import *

# Create your views here.
def index(request):
    latest_poll_list=Poll.objects.order_by('-pub_date')[:5]
    template=loader.get_template('polls/index.html')
    context=RequestContext(request,{
        'latest_poll_list': latest_poll_list,
    })
    return(HttpResponse(template.render(context)))





def detail(request, poll_id):
    poll=get_object_or_404(Poll, pk=poll_id)
    return(render(request,'polls/detail.html', {'poll': poll}))




def results(request, poll_id):
    return(HttpResponse('You are looking at the result of poll %s.' % poll_id))
def vote(request, poll_id):
    return(HttpResponse('You are voting on poll %s.'%poll_id))

django/tutorial/mysite/polls/templates/polls/detail.html
<h1>{{poll.question}}</h1>
		{%if error_message%}<p><strong>{{error_message}}</strong></p>{%endif%}
		<form action="{%url 'polls:vote' poll.id%}" method="post">
			{%csrf_token%}
			{%for choice in poll.choice_set.all%}
				<input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{choice.id}}" />
				<label for="choice{{forloop.counter}}">{{choice.choice_text}}</label><br />
			{%endfor%}
			<input type="submit" value="Vote" />
			</form>

django/tutorial/mysite/polls/templates/polls/index.html
{%if latest_poll_list%}
		<ul>
			{%for poll in latest_poll_list%}
				<li><a href="{% url 'polls:detail' poll.id %}">{{poll.question}}</a></li>
			{%endfor%}
			</ul>
		{%else%}
			<p>No Polls are available</p>
		{%endif%}